language: node_js
node_js: 11.15.0
install:
  - npm install
  - npm run setup
  - npm run build
  - npm run browserTest:build
script:
  - npm run test-rpc
  - npm run browserTest:run
deploy:
  - provider: script
    script: 'git checkout master && npm run publish:canary'
    email: '$NPM_EMAIL'
    api_token: '$NPM_API_TOKEN'
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: 'git checkout release && npm run publish:release'
    email: '$NPM_EMAIL'
    api_token: '$NPM_API_TOKEN'
    skip_cleanup: true
    on:
      branch: release
